import SwiftUI
#if canImport(ImagePlayground)
import ImagePlayground
#endif

protocol ImageGeneratorProtocol {
    func generateImage(prompt: String) async throws -> UIImage
}

class ImageGenerator: ImageGeneratorProtocol {
    func generateImage(prompt: String) async throws -> UIImage {
        #if canImport(ImagePlayground)
        if #available(iOS 18.2, macOS 15.2, *) {
            // Correct availability check for Apple Intelligence Image Playgrounds
            guard ImagePlaygroundViewController.isAvailable else {
                print("Image Playground is not available on this device/environment. Falling back to mock.")
                return try await fallbackMockGeneration()
            }
            
            let creator = try await ImageCreator()

            // Standardizing on the Illustration style for a "painterly" feel as per design plan
            let concepts: [ImagePlaygroundConcept] = [.text(prompt)]

            // Request images as an async sequence
            let stream = creator.images(for: concepts, style: .illustration, limit: 1)
            
            var firstImage: ImageCreator.CreatedImage?
            for try await image in stream {
                firstImage = image
                break
            }

            guard let created = firstImage else {
                throw NSError(domain: "ImageGenerator", code: 404, userInfo: [NSLocalizedDescriptionKey: "No images generated by Apple Intelligence"])
            }

            // Correct implementation using the native properties of ImageCreator.CreatedImage
            // The ‘cgImage’ property is the standard way to retrieve the result.
            return UIImage(cgImage: created.cgImage)
        } else {
            return try await fallbackMockGeneration()
        }
        #else
        return try await fallbackMockGeneration()
        #endif
    }
    
    private func fallbackMockGeneration() async throws -> UIImage {
        // Simulating delay for older systems or missing framework
        try await Task.sleep(nanoseconds: 2 * 1_000_000_000)
        return UIImage(systemName: "person.crop.rectangle.fill")?.withTintColor(.systemIndigo) ?? UIImage()
    }
}

